name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    # Only run on master branch
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build extension
        run: pnpm build

      - name: Package extension
        run: pnpm package

      # Get version type from commit message
      - name: Get version type from commit message
        id: version-type
        run: |
          VERSION_TYPE=$(node scripts/version.js get-version-type)
          echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT

      # Increment version in version.json (source of truth) and remove from package.json
      - name: Increment version
        id: increment-version
        run: |
          NEW_VERSION=$(node scripts/version.js increment ${{ steps.version-type.outputs.version_type }})
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Commit the version bump
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.json package.json
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push

      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG=$(node scripts/version.js changelog)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.increment-version.outputs.new_version }}
          name: Release v${{ steps.increment-version.outputs.new_version }}
          body: |
            ## Changes in this release
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            
            Download the extension from the [Chrome Web Store](https://chrome.google.com/webstore/detail/url-manipulator/your-extension-id).
          files: |
            dist/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 